# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import file_service.files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('owner', models.UUIDField(null=True, verbose_name='Owner')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=file_service.files.models.create_unique_filename, verbose_name='File')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
    ]
