# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mimetype',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mimetype'),
        ),
        migrations.AddField(
            model_name='file',
            name='origin_filename',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Original filename'),
        ),
        migrations.AddField(
            model_name='file',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Ready'),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0, verbose_name='File size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(
                choices=[('OTHER', 'Other'), ('AUDIO', 'Audio'), ('IMAGE', 'Image')], default='OTHER',
                max_length=24, verbose_name='Type'
            ),
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
