# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 15:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20171024_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Meta data'),
        ),
    ]
