# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 11:50
from __future__ import unicode_literals
import mimetypes
import os

from django.db import migrations

def populate_fields(apps, schema_editor):
    FileModel = apps.get_model('files', 'File')
    for row in FileModel.objects.all():
        row.filename = row.file.name

        if row.file and os.path.isfile(row.file.path):
            row.size = row.file.size

            mimetype, encoding = mimetypes.guess_type(row.file.path)

            if mimetype:
                maintype, subtype = mimetype.split('/')

                if maintype == 'audio':
                    row.type = 'AUDIO'
                elif maintype == 'image':
                    row.type = 'IMAGE'
                else:
                    row.type = 'OTHER'

        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_metadata'),
    ]

    operations = [
        migrations.RunPython(populate_fields, reverse_code=migrations.RunPython.noop),
    ]
