# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import file_service.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20171102_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=file_service.files.models.create_unique_filename, validators=[file_service.files.models.validate_file_extention], verbose_name='File'),
        ),
    ]
