# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def update_types(apps, schema_editor):
    File = apps.get_model("files", "File")
    FileType = apps.get_model("files", "FileType")

    FileType.objects.get_or_create(id='IMAGE', mime='image/jpeg')
    FileType.objects.get_or_create(id='AUDIO', mime='audio/x-hx-aac-adts')

    File.objects.filter(type='OTHER').update(type=None)


def revert_types(apps, schema_editor):
    File = apps.get_model("files", "File")

    File.objects.filter(type=None).update(type='OTHER')


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20180615_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('mime', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='file', name='type',
            field=models.CharField(blank=True, null=True, max_length=24, verbose_name='Type'),
        ),
        migrations.RunPython(update_types, revert_types, atomic=False),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.FileType'),
        ),
    ]
