# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-23 19:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_filetextcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetemplate',
            name='example_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Meta data'),
        ),
    ]
