# Generated by Django 3.0.3 on 2020-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_filetextcontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileextension',
            name='owner',
            field=models.IntegerField(null=True, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='filetemplate',
            name='owner',
            field=models.IntegerField(null=True, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='filetype',
            name='owner',
            field=models.IntegerField(null=True, verbose_name='Owner'),
        ),
    ]