# Generated by Django 3.0.3 on 2020-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20200422_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.IntegerField(null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='files.Tag'),
        ),
    ]
